### ISSUE TITLE
Trying to run the script under Windows 10 - 'could not find the specified file'

### ISSUE THREAD

**Issue by ivellios1988** [chaofengc/PSFRGAN#10]
Well, I know that in requirements you stated that it would be best choice to test your script in Ubuntu, but I decided to try running it under Windows 10 (64-bit edition). Despite my xtremely poor skills in Python, installation proved successful, however, when I tried to process test images I ran into following errors...

```
(base) C:\PSFRGAN-master poprawianie twarzy w HQ>python test_enhance_single_unalign.py --test_img_path ./test_dir/test_hzgg.jpg --results_dir test_hzgg_results --gpus 1
Traceback (most recent call last):
  File "test_enhance_single_unalign.py", line 93, in <module>
    opt = TestOptions().parse()
  File "C:\PSFRGAN-master poprawianie twarzy w HQ\options\base_options.py", line 141, in parse
    opt.gpu_ids = utils.get_gpu_memory_map()[1][:opt.gpus]
  File "C:\PSFRGAN-master poprawianie twarzy w HQ\utils\utils.py", line 123, in get_gpu_memory_map
    result = subprocess.check_output(
  File "C:\Users\ivell\anaconda3\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\ivell\anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\ivell\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ivell\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku
```

Last line says 'could not find the specified file'.

**Comment by chaofengc** [comment]
It seems that you have no GPU to run the code. Please try to run the code with CPU by specify the `--gpus 0`

**Comment by ivellios1988** [comment]
Thanks, with CPU it works like a charm. Looks like my GPU (NVIDIA GeForce 940MX) isn't supported.

Now I came across another issue, this time I tried to process a whole folder and I got this error:

```
(base) C:\PSFRGAN-master poprawianie twarzy w HQ>python align_and_crop_dir.py --src_dir test_dir_batch --results_dir test_dir_batch_results
Traceback (most recent call last):
  File "align_and_crop_dir.py", line 81, in <module>
    align_and_save_dir(src_dir, save_dir, use_cnn_detector=not args.not_use_cnn_detector)
  File "align_and_crop_dir.py", line 62, in align_and_save_dir
    points = get_points(img, detector, sp)
  File "align_and_crop_dir.py", line 12, in get_points
    dets = detector(img, 1)
MemoryError: bad allocation
```

I tried to process 7 pictures but ended up with whole RAM consumed, an enormously huge pagefile, and the above error message.

**Comment by chaofengc** [comment]
You may try Google Colab #4 if your machine does not satisfy the hardware requirement. 
For the second issue, it is likely that you have a test image with big resolution, and it takes too much RAM for the dlib face detector to process it. Also, this may be solved using Google Colab.
