### ISSUE TITLE
Google collab?

### ISSUE THREAD

**Issue by shadowzoom** [chaofengc/PSFRGAN#4]
Hi there, can anybody pls make a google collab version?

**Comment by woctezuma** [comment]
This is the code:
```
!git clone https://github.com/chaofengc/PSFR-GAN.git
%cd PSFR-GAN/
%pip install -r requirements.txt
%mkdir -p pretrain_models
%cd pretrain_models/
!gdown --id 1UcTeI_-YmQeNypHW98VRuIF13xEPmPWm
!gdown --id 1UhzMSORSul88iVfSYQYuEal83lEoNN7l
!gdown --id 1Unn2eznkclqUhK_o50YUyaV7eoTE4Su3
!gdown --id 1Uxb-nw04fyjABEaZCgeYgGrR4fIu7VUf
!gdown --id 1UiHeUHVNKiEq_s5dcBv6jez6TqrAduMg
%cd /content/PSFR-GAN/
!wget https://i.imgur.com/7gPVDg4.png
test_img_path = '7gPVDg4.png'
!python test_enhance_single_unalign.py --test_img_path {test_img_path} --results_dir results --gpus 1
```

An issue is an `AssertionError` arises:
```
Traceback (most recent call last):
  File "test_enhance_single_unalign.py", line 93, in <module>
    opt = TestOptions().parse()
  File "/content/PSFR-GAN/options/base_options.py", line 144, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 245, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 149, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 63, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.
```

**Comment by woctezuma** [comment]
https://gist.github.com/woctezuma/20e4dd3d49da09bf339d909f29c5527e

**Comment by woctezuma** [comment]
Code: https://gist.github.com/woctezuma/20e4dd3d49da09bf339d909f29c5527e

Results:

<img alt="Input" src="https://i.imgur.com/7gPVDg4.png" width="400"><img alt="Output" src="https://i.imgur.com/Zm5lIhq.png" width="400">

<img alt="LG" src="https://i.imgur.com/iuibr7C.png" height="150"><img alt="LG" src="https://i.imgur.com/HUcTrAo.png" height="150"><img alt="LG" src="https://i.imgur.com/YlYUVyo.png" height="150">

<img alt="HQ" src="https://i.imgur.com/8iJ3e8c.png" height="150"><img alt="HQ" src="https://i.imgur.com/1ekaCL7.png" height="150"><img alt="HQ" src="https://i.imgur.com/c9ejcDc.png" height="150">

**Comment by chaofengc** [comment]
🙏 Millions of thanks for providing the demo ! @woctezuma
