### ISSUE TITLE
Dlib Import error

### ISSUE THREAD

**Issue by viktor02** [chaofengc/PSFRGAN#5]
Program gives this error, I found a solution on the Internet that you need to install cblas, however, even after installation, nothing has changed
```
❯ python align_and_crop_dir.py --src_dir test_dir --results_dir test_dir_align_results
Traceback (most recent call last):
  File "align_and_crop_dir.py", line 1, in <module>
    import dlib
  File "/run/media/viktor/Torrent/NeuralNetworks/PSFRGAN/venv/lib/python3.8/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: /run/media/viktor/Torrent/NeuralNetworks/PSFRGAN/venv/lib/python3.8/site-packages/_dlib_pybind11.cpython-38-x86_64-linux-gnu.so: undefined symbol: cblas_dtrsm
```
```
❯ pip freeze
absl-py==0.10.0
astunparse==1.6.3
certifi==2020.6.20
cycler==0.10.0
decorator==4.4.2
dlib==19.21.0
future==0.18.2
gast==0.3.3
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
imageio==2.9.0
imgaug==0.4.0
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib==3.3.2
networkx==2.5
numpy==1.19.2
opencv-python==4.4.0.44
opt-einsum==3.3.0
Pillow==7.2.0
protobuf==3.13.0
pyparsing==2.4.7
python-dateutil==2.8.1
PyWavelets==1.1.1
scikit-image==0.17.2
scipy==1.4.1
Shapely==1.7.1
six==1.15.0
tensorboard==1.15.0
tensorboardX==2.1
tensorflow==2.3.1
tensorflow-estimator==2.3.0
termcolor==1.1.0
tifffile==2020.9.22
torch==1.5.1
torchvision==0.6.1
tqdm==4.50.0
Werkzeug==1.0.1
wrapt==1.12.1
```
```
❯ pacman -Ss cblas
extra/cblas 3.9.0-3 [Installed]
    C interface to BLAS
``` 
```
❯ neofetch --off
viktor@viktor-p61usb3b3 
----------------------- 
OS: Manjaro Linux x86_64 
Host: P61-USB3-B3 
Kernel: 5.8.6-1-MANJARO 
Uptime: 49 mins 
Packages: 1118 (pacman) 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: GNOME 3.36.6 
WM: Mutter 
WM Theme: Matcha-dark-sea 
Theme: Nordic-darker [GTK2/3] 
Icons: Papirus-Dark-nordic-blue-folders [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-2500 (4) @ 3.700GHz 
GPU: NVIDIA GeForce GTX 1080 
Memory: 3115MiB / 15995MiB 
```

**Comment by chaofengc** [comment]
I am not sure what is the problem. I used anaconda with python 3.7. You may try to use anaconda to manage your environment.

**Comment by chaofengc** [comment]
You may also try the Google Colab #4

**Comment by szekelybalint** [comment]
try
```
pip install cmake
conda install -c conda-forge dlib
```
